### ISSUE TITLE
Not working for flutter web projects

### ISSUE THREAD

**Issue by CoconutDigital** [fluttercommunity/font_awesome_flutter#54] opened 2019-09-10 00:52 UTC
Hi There,

I would love to be able to use this plugin for my flutter web projects. Is this something you guys will be looking into soon?

**Comment by ercangurevin** [comment] 2019-09-14 14:43
![Screenshot from 2019-09-14 17-42-14](https://user-images.githubusercontent.com/46600823/64909594-0afbbb00-d717-11e9-9cfd-3cb66b374b1c.png)

Hi, The fonts does not render in flutter web projects. They looks like this.

**Comment by michaelspiss** [comment] 2019-09-14 17:08
Ok now it's getting interesting - it works fine for me in chrome (right), but I was able to reproduce the issue in firefox (left). @CoconutDigital, @ercangurevin do you experience this in chrome as well? I'm looking into this

![screenshot](https://user-images.githubusercontent.com/17252710/64911521-0e953f00-d723-11e9-9735-ed9630ecb8e2.png)

**Comment by michaelspiss** [comment] 2019-09-18 17:08
This issue is fixed if @CoconutDigital and @ercangurevin also experienced this issue in firefox only. This package works with flutter web.

**Comment by ercangurevin** [comment] 2019-09-19 06:37
Hi, I have still problem. I've tried it on 3 browser; Chrome, Firefox and Opera. Here are the results.
![Screenshot from 2019-09-19 09-34-49](https://user-images.githubusercontent.com/46600823/65219354-10635780-dac1-11e9-95ef-63cc5f6f1fb1.png)
![Screenshot from 2019-09-19 09-35-49](https://user-images.githubusercontent.com/46600823/65219356-10635780-dac1-11e9-84d8-e014626fe868.png)

**Comment by michaelspiss** [comment] 2019-09-19 07:52
Could you do a `flutter clean` and rebuild just to make sure there is nothing cached from older versions? If it still persists after that, please post the parts of the sample project you modified and I will try to reproduce again.

**Comment by ercangurevin** [comment] 2019-09-19 08:03
After clean it's still same. I even tried on new project but no luck.

**Comment by michaelspiss** [comment] 2019-09-19 08:17
Ok that's really strange. What value did you change the button icon to?

**Comment by Ahmadre** [comment] 2019-09-30 13:29
Solved it like this:

1. Use 
```dart
    IconData(0xf183, fontFamily: 'FontAwesomeSolid'),
```
instead FontAwesomeIcons.male for example. Notice, that there're three different Font-Packages: Brands, Solid and Regular! So the codePoint here: 0xf183 is only available in the Solid Font-Package!

2. Add these lines to your pubspec.yaml:
```dart
- family: FontAwesomeRegular
      fonts:
        - asset: assets/fonts/fa-regular-400.ttf
          style: normal
    - family: FontAwesomeBrands
      fonts:
        - asset: assets/fonts/fa-brands-400.ttf
          style: normal
    - family: FontAwesomeSolid
      fonts:
        - asset: assets/fonts/fa-solid-900.ttf
          style: normal
```

3. Add these lines to your web/assets/fonts/FontManifest.json file:
```dart
    {"fonts":[{"asset":"fonts/fa-regular-400.ttf"}],"family":"FontAwesomeRegular"},
    {"fonts":[{"asset":"fonts/fa-brands-400.ttf"}],"family":"FontAwesomeBrands"},
    {"fonts":[{"asset":"fonts/fa-solid-900.ttf"}],"family":"FontAwesomeSolid"}
```

4. Done! Here's my flutter web app:
<img width="464" alt="Bildschirmfoto 2019-09-30 um 15 29 05" src="https://user-images.githubusercontent.com/18512224/65883329-1d245d00-e397-11e9-9cb7-9a18f772640f.png">

Good luck!

**Comment by bl4ckcrow** [comment] 2020-01-15 21:42
In my case, I solved it like this:

1. Add these lines in the **FontManifest.json** file
{
    "family": "packages/font_awesome_flutter/FontAwesomeBrands",
    "fonts": [
      {
        "weight": 400,
        "asset": "packages/font_awesome_flutter/lib/fonts/fa-brands-400.ttf"
      }
    ]
  },
  {
    "family": "packages/font_awesome_flutter/FontAwesomeRegular",
    "fonts": [
      {
        "weight": 400,
        "asset": "packages/font_awesome_flutter/lib/fonts/fa-regular-400.ttf"
      }
    ]
  },
  {
    "family": "packages/font_awesome_flutter/FontAwesomeSolid",
    "fonts": [
      {
        "weight": 900,
        "asset": "packages/font_awesome_flutter/lib/fonts/fa-solid-900.ttf"
      }
    ]
  }

2. Run the command **flutter clean** and rebuild

**DONE**
![image](https://user-images.githubusercontent.com/57684868/72473849-2d791000-37ad-11ea-995a-6c2690271235.png)

Hope this helps !

**Comment by brianegan** [comment] 2020-02-18 13:15
Hey all, I'm going to tentatively close this issue since I think the Flutter team has done some good work ensuring fonts will be included in the FontManifest.json by default now. Thanks for all the info!

**Closed by brianegan** 2020-02-18 13:15 UTC
