### ISSUE TITLE
Missing sharp solid style in pro version?

### ISSUE THREAD

**Issue by steve3d** [fluttercommunity/font_awesome_flutter#224] opened 2022-09-12 12:32 UTC
fontawesome-pro 6.2's major change is the sharp solid style icons.

Then I tried to follow the readme to create my own pro version, and I found that  the sharp solid style are completely ignored.

here is the styles: https://fontawesome.com/search?o=r&s=solid&f=sharp

as you can see, the sharp solid is just a solid variation, but in generated pubspec.yaml:
```
flutter:
  fonts:
    - family: FontAwesomeBrands
      fonts:
        - asset: lib/fonts/fa-brands-400.ttf
          weight: 400
    - family: FontAwesomeRegular
      fonts:
        - asset: lib/fonts/fa-regular-400.ttf
          weight: 400
    - family: FontAwesomeSolid
      fonts:
        - asset: lib/fonts/fa-solid-900.ttf
          weight: 900
    - family: FontAwesomeLight
      fonts:
        - asset: lib/fonts/fa-light-300.ttf
          weight: 300
    - family: FontAwesomeThin
      fonts:
        - asset: lib/fonts/fa-thin-100.ttf
          weight: 100
```

there is no `fa-sharp-solid-900.ttf`, I think the simplest way and maybe annoying way is duplicate and add `sharp` prefix to all solid icons. like `FontAwesomeIcons.solidZero` and `FontAwesomeIcons.sharpSolidZero`? indeed a little strange  😅

**Comment by michaelspiss** [comment] 2022-09-12 13:56
Hi, sharp is not supported with the newest release because the icons are limited to pro. I don't own a pro license and won't buy one just to then support a paid feature for free ([we've discussed this thoroughly with duotone support](https://github.com/fluttercommunity/font_awesome_flutter/issues/192#issuecomment-1073003668)). This means pro icons are supported solely by the community, more explicitly by people who already own/have access to a license.

Now let's get to the good part:
You may be able to get this working the following way:
add these lines to your pubspec under `fonts`:
```
    - family: FontAwesomeSharpSolid
      fonts:
        - asset: lib/fonts/fa-sharp-solid-900.ttf
          weight: 900
```
This makes sure flutter knows about the font file. 

Now take a look at the icons.json file provided in the metadata folder. Check how the sharp icons are identified - in the best case, there only is a new style named sharp-solid or something. Otherwise, this would require significant changes to the configurator tool.

I may be able to assist further once I have this piece of information.

**Comment by steve3d** [comment] 2022-09-12 14:07
Thanks for the quick response, but your suggestion will not work, in version 6.2, every solid icon has a sharp version, so there is no any information in the `icons.json`.  e.g, `360-degrees` icon in `icons.json`:
```
  "360-degrees": {
    "changes": [
      "6.0.0-beta1",
      "6.2.0"
    ],
    "label": "360 Degrees",
    "search": {
      "terms": []
    },
    "styles": [
      "solid",
      "regular",
      "light",
      "thin",
      "duotone"
    ],
    "unicode": "e2dc",
    "voted": false
  },
```

and here is the web preview url for this icon : https://fontawesome.com/icons/360-degrees?s=solid&f=classic

as you can see, if there is a solid icon, then the sharp solid version exists.

**Comment by steve3d** [comment] 2022-09-12 14:54
in order to the this sharp solid version, you might also need to check if this is a pro version later than 6.2.0, in previous 6.x version, there is no sharp solid version, I think fontaweome introduced the icon families, like classic icons, now sharp version for only solid, then might be sharp regular. 

like this changelog line:
```
Two new files are now available from the metadata directory: icon-families.json and icon-families.yml which are restructured to support Font Awesome Families.
```

**Comment by michaelspiss** [comment] 2022-09-12 14:58
That's why I'd check for the sharp font file directly.

Not sure what font awesome families are supposed to be - I guess classic and sharp?

**Comment by steve3d** [comment] 2022-09-14 01:31
here is the font-families.json icon example:
```
{
  "0": {
    "changes": [
      "6.0.0-beta1",
      "6.2.0"
    ],
    "ligatures": [],
    "unicode": "30",
    "label": "0",
    "voted": false,
    "svgs": {
      "classic": {
        "solid": {
          "lastModified": 1660321776,
          "raw": "",
          "viewBox": [
            0,
            0,
            320,
            512
          ],
          "width": 320,
          "height": 512,
          "path": ""
        },
        "regular": {
          "lastModified": 1660014469,
          "raw": "",
          "viewBox": [
            0,
            0,
            320,
            512
          ],
          "width": 320,
          "height": 512,
          "path": ""
        },
        "light": {
          "lastModified": 1660014469,
          "raw": "",
          "viewBox": [
            0,
            0,
            320,
            512
          ],
          "width": 320,
          "height": 512,
          "path": ""
        },
        "thin": {
          "lastModified": 1660014469,
          "raw": "",
          "viewBox": [
            0,
            0,
            320,
            512
          ],
          "width": 320,
          "height": 512,
          "path": ""
        }
      },
      "duotone": {
        "solid": {
          "lastModified": 1660014469,
          "raw": "",
          "viewBox": [
            0,
            0,
            320,
            512
          ],
          "width": 320,
          "height": 512,
          "path": [
            
          ]
        }
      },
      "sharp": {
        "solid": {
          "lastModified": 1660321776,
          "raw": "",
          "viewBox": [
            0,
            0,
            320,
            512
          ],
          "width": 320,
          "height": 512,
          "path": ""
        }
      }
    },
    "familyStylesByLicense": {
      "free": [
        {
          "family": "classic",
          "style": "solid"
        }
      ],
      "pro": [
        {
          "family": "classic",
          "style": "solid"
        },
        {
          "family": "classic",
          "style": "regular"
        },
        {
          "family": "classic",
          "style": "light"
        },
        {
          "family": "classic",
          "style": "thin"
        },
        {
          "family": "duotone",
          "style": "solid"
        },
        {
          "family": "sharp",
          "style": "solid"
        }
      ]
    }
  },
  ...
```

I've removed `raw` and `path` content, those are svg related, I have the pro license, so how can I provide this sharp font to you?

**Comment by michaelspiss** [comment] 2022-09-19 16:33
Thanks, it's good to know what this file looks like.

I won't work on this for now due to the reasons laid out above and even though it's very nice of you to offer to share the required files with me, it would violate font awesome's licensensing agreement.

Feel free to work on this and provide a pull request once you have a working solution, I'd be happy to merge it.

**Comment by aebrahim** [comment] 2023-11-29 22:12
@michaelspiss I would be happy to pay for 2 years of font awesome pro for you if that helps you implement this feature, but I'm a little surprised the font awesome folks haven't offered to give you a free perpetual license given how awesome this package is and your amazing work on it.

**Comment by michaelspiss** [comment] 2023-12-21 15:13
Hey @aebrahim and thanks for the offer! We already contacted them and they declined. By now I've taken the stance that the community should not pay to implement their features out of their pocket. Because even if the license is paid for, it is still a lot of work to make sure the features are implemented correctly and stay up to date with their changes. I'd rather not introduce a feature than having to deal with feature regression/having to remove them again once people are already using them. We did this with Duotone icons for a while, but had to drop support exactly because of these reasons. In my opinion, if they want to extend their reach to the flutter ecosystem officially, they should also pay for the cost of implementation of their paid features.

We are committed to enable the use font awesome icons on flutter for the free version. When it comes to the pro icons, the configurator gives a lot of freedom already, but we will not implement any additions to the current state ourselves. We are happy to take contributions in form of pull requests however :)

**Comment by JudahMcNicholl** [comment] 2024-04-04 02:50
Hi,
So I wanted to use the Sharp Icons through this package also, I have put a PR in on how to do this
https://github.com/fluttercommunity/font_awesome_flutter/pull/261
I don't expect this to be accepted but I hope that people will be able to use these code changes to get started using Sharp Icons.

Key points: 
Copy in the contents of font-families.json from your downloaded font-awesome web into lib/fonts/icons.json
It it backwards compatible as it checks relevant keys in the icons.json

**Comment by michaelspiss** [comment] 2024-11-03 17:31
Hey everyone! Thanks to @JudahMcNicholl, sharp icons are now supported with version 10.8.0

**Closed by michaelspiss** 2024-11-03 17:31 UTC
