### ISSUE TITLE
Certain icons are not displayed

### ISSUE THREAD

**Issue by ResoDev** [fluttercommunity/font_awesome_flutter#97] opened 2020-06-06 09:47 UTC
Hello!
I followed the process of adding PRO icons carefully. All the fonts are in the appropriate `lib/fonts` folder.

What happens is that certain types of the icons are missing. Sometimes it's only the solid version that is not displayed, other times it's the solid and regular version. Interestingly, the light version seems to be displayed at all times.

![screenshot_17](https://user-images.githubusercontent.com/18404788/83941373-1209b280-a7eb-11ea-8693-d163c66c3f6d.png)

I've checked the font TTF files and, indeed, all of the glyphs are present. The code generated by the `update.bat` script seems to be correct. For example:
```dart
  static const IconData airConditioner = const IconDataRegular(0xf8f4);
  static const IconData solidAirConditioner = const IconDataSolid(0xf8f4);
  static const IconData lightAirConditioner = const IconDataLight(0xf8f4);
  static const IconData duotoneAirConditioner = const IconDataDuotone(0xf8f4);
```

**Comment by michaelspiss** [comment] 2020-06-06 10:15
Hi, please run `flutter clean`, `flutter pub get` and rebuild the project to make sure this has nothing to do with caching. If it doesn't work, please include the output of `flutter doctor -v` and your font awesome version and I will try to reproduce this.

**Comment by ResoDev** [comment] 2020-06-06 11:31
I've run the commands countless times. Still, the result is the same.
The Font Awesome version I use is 5.13.0 and the flutter doctor output is:
```
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18362.836], locale en-US)
    • Flutter version 1.17.2 at C:\Flutter\flutter
    • Framework revision 5f21edf8b6 (9 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Development\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Development\Android\sdk
    • ANDROID_SDK_ROOT = C:\Development\Android\sdk
    • Java binary at: C:\Android Studio\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Android Studio\android-studio-canary
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Android Studio (version 3.6)
    • Android Studio at C:\Android Studio\android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\mreso\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

**Comment by michaelspiss** [comment] 2020-06-06 12:19
Duotone icons not displaying correctly was my mistake, sorry for that - pull request pending for some last tests. Howevery, I cannot reproduce the issue with the other icons not displaying. Maybe try `flutter upgrade` and test it with version 1.17.3?

**Comment by ResoDev** [comment] 2020-06-06 20:00
I can confirm that the issue still occurs on 1.17.3.

**Comment by michaelspiss** [comment] 2020-06-07 17:28
Very interesting. 
It seems like it does not load the whole font, but only some symbols (?) - otherwise it would display at least a ☒ instead of just white space. Sadly, I cannot reproduce this on my machine - all icons (except duotone) show up as they should (tested with flutter 1.17.3 and font awesome 5.13.0). 

I will take some wild guesses here, but that's all I have left.
1. You are not using the original regular/solid font files, but a minified version where icons have been removed (I guess they'd show up blank? - not tested)
2. It has something to do with missing android licenses, as this is the only other thing I see in `flutter doctor` that could possibly have something to to with "failed" builds (??)

Other than that I really don't know how this could happen...

**Comment by omartinma** [comment] 2020-07-01 12:22
Hello,

First thanks for the package. I think i have similar issue, but instead of empty is showing ? symbol in certain icons in the regular version always. So far the others everything perfect.

![image](https://user-images.githubusercontent.com/11978998/86243216-454f1f80-bba6-11ea-9fb7-217801bff61a.png)

**Comment by michaelspiss** [comment] 2020-07-01 17:06
Is this the example app or your own? Could you give some examples as to which icons don't show up?

**Comment by omartinma** [comment] 2020-07-02 00:35
It is in my project but i just tried in the example project and same result:
![image](https://user-images.githubusercontent.com/11978998/86303528-53d02200-bc0c-11ea-8dce-63092339c1c7.png)

In case it helps:
Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.2 19C57, locale es-ES)

**Comment by michaelspiss** [comment] 2020-07-02 07:43
Thanks for the picture and version information, it helps a lot. Do airConditioner, solidAirConditioner, and airFreshener also display the question mark for you?

**Comment by omartinma** [comment] 2020-07-02 11:54
airFreshener yes, the others 2 are displayed correctly

**Comment by jamesdixon** [comment] 2020-09-29 19:30
Hey all! Any updates on this one? Just ran into this when trying to use Duotone icons

**Comment by michaelspiss** [comment] 2020-10-04 15:22
Sadly not, I'm still unable to reproduce. Any further information is welcome.

**Comment by davidcabreraftf** [comment] 2021-01-07 06:55
The first situation with no icons, and only blank spaces just happened to me.  And was caused because I had a version mismatch between the pro asset files and the regular ones

I had the package working perfectly (FontAwesome 5.13.3 ) , until today I found the build issue with tree shake, so I had to update. When I updated, I copied the free .ttf files from the project which uses (5.15.1) but forgot to update PRO files.

I upgraded PRO files to match the same version, re ran the update script and it worked fine

**Comment by davidgcs11** [comment] 2021-01-07 07:05
I was able to reproduce the first situation with some icons missing, except the PRO ones (duotone and light). And was caused because I had a version mismatch between my pro asset files and the regular ones.

I had the package working perfectly (FontAwesome 5.13.3 ) , until today I found the build issue with tree shake, so I had to update. When I updated, I copied the regular .ttf files from the project which uses (5.15.1) but forgot to update PRO files to this new version. Since my icon.json (from pro version was from 5.13.3), I guess it wasn't recognizing properly the regular icons with 5.15.1

Once I upgraded PRO files to match the same version, and re ran the update script, it was back to normal.

@michaelspiss  It might be good to have this on the readme. That whenever using PRO files, we need to make sure that version it's the same the free ones

**Comment by michaelspiss** [comment] 2021-01-07 15:47
Thank you @davidgcs11 for posting your solution! The `icons.json` tells the updater which icons are available and where they are - so it makes sense that icons were missing in your case. I've added a note to the readme's pro icon section.

A version mismatch between the `icons.json` and any of the `.ttf` font files might be the problem for others here as well. It would certainly explain why only some of the icons are missing. If someone affected could confirm, that'd be great!

I'd also be interested whether this issue still persists in flutter 1.22, as icon tree shaking should throw an error in this case.

**Comment by michaelspiss** [comment] 2021-03-10 12:13
Closing since this has seemingly been fixed or just isn't happening anymore. If anyone encounters this problem again, feel free to reopen.

**Closed by michaelspiss** 2021-03-10 12:13 UTC
Labels: Generator, bug, help wanted
